typedef struct _anon0;
typedef struct _anon1;
typedef struct _anon2;
typedef struct _anon3;
typedef struct tagPALETTEENTRY;


typedef unsigned short type_0[6];
typedef tagPALETTEENTRY type_1[24];
typedef unsigned short type_2[6];
typedef unsigned short type_3[6];
typedef tagPALETTEENTRY type_4[24];
typedef unsigned short type_5[6];
typedef tagPALETTEENTRY type_6[24];
typedef unsigned short type_7[6];
typedef unsigned short type_8[6];
typedef _anon0 type_9[2];
typedef tagPALETTEENTRY type_10[24];
typedef unsigned short type_11[6];
typedef unsigned short type_12[6];
typedef unsigned short type_13[6];
typedef unsigned short type_14[6];
typedef tagPALETTEENTRY type_15[8];
typedef unsigned short type_16[32];
typedef _anon2 type_17[10];
typedef unsigned short type_18[6];
typedef unsigned short type_19[6];
typedef tagPALETTEENTRY type_20[24];
typedef unsigned short type_21[8];
typedef unsigned short* type_22[38];
typedef tagPALETTEENTRY type_23[24];
typedef unsigned short type_24[6];
typedef unsigned short type_25[6];
typedef tagPALETTEENTRY type_26[24];
typedef unsigned short type_27[6];
typedef unsigned short type_28[6];
typedef tagPALETTEENTRY type_29[24];
typedef unsigned short type_30[6];
typedef unsigned short type_31[6];
typedef tagPALETTEENTRY type_32[24];
typedef unsigned short type_33[6];
typedef tagPALETTEENTRY type_34[24];
typedef unsigned short type_35[6];
typedef unsigned short type_36[6];
typedef tagPALETTEENTRY type_37[24];
typedef unsigned short type_38[6];
typedef tagPALETTEENTRY type_39[24];
typedef unsigned short type_40[6];
typedef unsigned short type_41[6];
typedef tagPALETTEENTRY type_42[24];
typedef unsigned short type_43[6];
typedef unsigned short type_44[6];
typedef tagPALETTEENTRY* type_45[2];
typedef unsigned short type_46[6];
typedef unsigned short type_47[6];
typedef tagPALETTEENTRY type_48[8];
typedef unsigned short type_49[6];
typedef tagPALETTEENTRY* type_50[32];
typedef unsigned short type_51[6];
typedef tagPALETTEENTRY type_52[24];
typedef unsigned short type_53[6];
typedef unsigned short type_54[6];
typedef tagPALETTEENTRY type_55[24];
typedef unsigned short type_56[6];
typedef unsigned short type_57[6];
typedef tagPALETTEENTRY type_58[24];
typedef unsigned short type_59[6];
typedef unsigned short type_60[6];
typedef tagPALETTEENTRY type_61[24];

struct _anon0
{
	short index;
	unsigned char etc;
	short hoffs;
	short hrevoffs;
	short voffs;
	short vrevoffs;
};

struct _anon1
{
	short mapnum;
	_anon0 aMapDat[2];
};

struct _anon2
{
	short timer;
	_anon1* paMapTbl;
};

struct _anon3
{
	short patnum;
	_anon2 aPatDat[10];
};

struct tagPALETTEENTRY
{
	unsigned char peRed;
	unsigned char peGreen;
	unsigned char peBlue;
	unsigned char peFlags;
};

_anon1 s_stand1_spr00;
_anon3 s_stand1_map;
_anon1 s_stand2_spr00;
_anon3 s_stand2_map;
_anon1 s_wait_spr00;
_anon1 s_wait_spr01;
_anon3 s_wait_map;
_anon1 s_run_spr00;
_anon1 s_run_spr01;
_anon1 s_run_spr02;
_anon1 s_run_spr03;
_anon1 s_run_spr04;
_anon1 s_run_spr05;
_anon3 s_run_map;
_anon1 s_stop_spr00;
_anon1 s_stop_spr01;
_anon1 s_stop_spr02;
_anon1 s_stop_spr03;
_anon3 s_stop_map;
_anon1 s_ball_spr00;
_anon1 s_ball_spr01;
_anon1 s_ball_spr02;
_anon1 s_ball_spr03;
_anon1 s_ball_spr04;
_anon3 s_ball_map;
_anon1 erun_spr00;
_anon1 erun_spr01;
_anon1 erun_spr02;
_anon1 erun_spr03;
_anon1 erun_spr04;
_anon1 erun_spr05;
_anon3 erun_map;
_anon1 estand_spr00;
_anon1 estand_spr01;
_anon1 estand_spr02;
_anon3 estand_map;
_anon1 estand2_spr00;
_anon1 estand2_spr01;
_anon1 estand2_spr02;
_anon3 estand2_map;
_anon1 ejump_spr00;
_anon3 ejump_map;
_anon1 ekiss_spr00;
_anon1 ekiss_spr01;
_anon1 ekiss_spr02;
_anon3 ekiss_map;
_anon1 ecatch_spr00;
_anon1 ecatch_spr01;
_anon3 ecatch_map;
_anon1 eheart_spr00;
_anon1 eheart_spr01;
_anon1 eheart_spr02;
_anon3 eheart_map;
_anon1 m_stand_spr00;
_anon3 m_stand_map;
_anon1 m_era_spr00;
_anon1 m_era_spr01;
_anon3 m_era_map;
_anon1 m_era2_spr00;
_anon1 m_era2_spr01;
_anon3 m_era2_map;
_anon1 m_fly1_spr00;
_anon1 m_fly1_spr01;
_anon3 m_fly1_map;
_anon1 m_brake_spr00;
_anon1 m_brake_spr01;
_anon3 m_brake_map;
_anon1 m_stop_spr00;
_anon1 m_stop_spr01;
_anon3 m_stop_map;
_anon1 m_furi_spr00;
_anon1 m_furi_spr01;
_anon3 m_furi_map;
_anon1 m_kamae_spr00;
_anon1 m_kamae_spr01;
_anon3 m_kamae_map;
_anon1 flick_spr00;
_anon1 flick_spr01;
_anon3 flick_map;
_anon1 hato_spr00;
_anon1 hato_spr01;
_anon3 hato_map;
_anon1 inco_spr00;
_anon1 inco_spr01;
_anon3 inco_map;
_anon1 pocky_spr00;
_anon1 pocky_spr01;
_anon3 pocky_map;
_anon1 ricky_spr00;
_anon1 ricky_spr01;
_anon3 ricky_map;
_anon1 sheep_spr00;
_anon1 sheep_spr01;
_anon3 sheep_map;
_anon1 pecky_spr00;
_anon1 pecky_spr01;
_anon3 pecky_map;
tagPALETTEENTRY lpgoodA[24];
tagPALETTEENTRY lpgoodB[24];
tagPALETTEENTRY lpgoodC[24];
tagPALETTEENTRY lpgoodD[24];
tagPALETTEENTRY lpgoodE[24];
tagPALETTEENTRY lpgoodF[24];
tagPALETTEENTRY lpgoodG[24];
tagPALETTEENTRY lpgoodH[24];
tagPALETTEENTRY lpgoodI[24];
tagPALETTEENTRY lpgoodJ[24];
tagPALETTEENTRY lpgoodK[24];
tagPALETTEENTRY lpgoodL[24];
tagPALETTEENTRY lpgoodM[24];
tagPALETTEENTRY lpgoodN[24];
tagPALETTEENTRY lpgoodO[24];
tagPALETTEENTRY lpgoodP[24];
tagPALETTEENTRY lpgoodQ[24];
tagPALETTEENTRY* lpbs_good[32];
tagPALETTEENTRY asc_col00[8];
tagPALETTEENTRY asc_col01[8];
tagPALETTEENTRY* asc_coltbl[2];
unsigned short lpbs_timer[32];
unsigned short _A[6];
unsigned short _E[6];
unsigned short _F[6];
unsigned short _B[6];
unsigned short _C[6];
unsigned short _D[6];
unsigned short _G[6];
unsigned short _H[6];
unsigned short _I[6];
unsigned short _J[6];
unsigned short _K[6];
unsigned short _L[6];
unsigned short _M[6];
unsigned short _N[6];
unsigned short _O[6];
unsigned short _P[6];
unsigned short _Q[8];
unsigned short _R[6];
unsigned short _S[6];
unsigned short _T[6];
unsigned short _U[6];
unsigned short _V[6];
unsigned short _W[6];
unsigned short _X[6];
unsigned short _Y[6];
unsigned short _Z[6];
unsigned short _0[6];
unsigned short _1[6];
unsigned short _2[6];
unsigned short _3[6];
unsigned short _4[6];
unsigned short _5[6];
unsigned short _6[6];
unsigned short _7[6];
unsigned short _8[6];
unsigned short _9[6];
unsigned short _TEN[6];
unsigned short* asc_maptbl[38];


