typedef struct tagPALETTEENTRY;


typedef tagPALETTEENTRY type_0[16];
typedef tagPALETTEENTRY type_1[16];
typedef tagPALETTEENTRY type_2[16];
typedef tagPALETTEENTRY* type_3[32];
typedef tagPALETTEENTRY type_4[16];
typedef tagPALETTEENTRY type_5[16];
typedef tagPALETTEENTRY type_6[16];
typedef tagPALETTEENTRY* type_7[2];
typedef tagPALETTEENTRY type_8[16];
typedef tagPALETTEENTRY type_9[16];
typedef tagPALETTEENTRY type_10[16];
typedef tagPALETTEENTRY type_11[16];
typedef tagPALETTEENTRY type_12[16];
typedef tagPALETTEENTRY type_13[16];
typedef tagPALETTEENTRY type_14[16];
typedef tagPALETTEENTRY type_15[16];
typedef tagPALETTEENTRY type_16[16];
typedef tagPALETTEENTRY type_17[16];
typedef tagPALETTEENTRY type_18[16];
typedef tagPALETTEENTRY type_19[16];
typedef tagPALETTEENTRY type_20[16];
typedef tagPALETTEENTRY type_21[16];
typedef tagPALETTEENTRY type_22[16];
typedef tagPALETTEENTRY type_23[16];
typedef tagPALETTEENTRY type_24[16];
typedef tagPALETTEENTRY type_25[16];
typedef tagPALETTEENTRY type_26[16];
typedef tagPALETTEENTRY type_27[64];
typedef tagPALETTEENTRY type_28[16];
typedef tagPALETTEENTRY type_29[16];
typedef tagPALETTEENTRY type_30[16];
typedef tagPALETTEENTRY type_31[16];
typedef short type_32[32];
typedef tagPALETTEENTRY type_33[16];
typedef tagPALETTEENTRY type_34[16];
typedef tagPALETTEENTRY type_35[16];
typedef tagPALETTEENTRY type_36[16];
typedef tagPALETTEENTRY type_37[16];
typedef tagPALETTEENTRY type_38[16];
typedef tagPALETTEENTRY type_39[16];
typedef tagPALETTEENTRY type_40[16];
typedef tagPALETTEENTRY type_41[16];
typedef tagPALETTEENTRY type_42[16];
typedef tagPALETTEENTRY type_43[16];
typedef tagPALETTEENTRY type_44[16];
typedef tagPALETTEENTRY type_45[16];
typedef tagPALETTEENTRY type_46[16];
typedef tagPALETTEENTRY type_47[16];
typedef tagPALETTEENTRY type_48[16];
typedef tagPALETTEENTRY type_49[16];
typedef tagPALETTEENTRY type_50[16];
typedef tagPALETTEENTRY type_51[16];
typedef tagPALETTEENTRY type_52[16];
typedef tagPALETTEENTRY type_53[16];
typedef tagPALETTEENTRY type_54[16];
typedef tagPALETTEENTRY type_55[16];
typedef tagPALETTEENTRY type_56[16];
typedef tagPALETTEENTRY type_57[16];
typedef tagPALETTEENTRY type_58[16];
typedef tagPALETTEENTRY type_59[16];
typedef tagPALETTEENTRY type_60[16];
typedef tagPALETTEENTRY type_61[16];
typedef tagPALETTEENTRY type_62[16];
typedef tagPALETTEENTRY type_63[16];
typedef tagPALETTEENTRY type_64[16];
typedef tagPALETTEENTRY type_65[16];
typedef tagPALETTEENTRY type_66[16];
typedef tagPALETTEENTRY type_67[16];
typedef tagPALETTEENTRY type_68[16];
typedef tagPALETTEENTRY type_69[16];
typedef tagPALETTEENTRY type_70[16];
typedef tagPALETTEENTRY type_71[16];
typedef tagPALETTEENTRY type_72[16];
typedef tagPALETTEENTRY** type_73[6];
typedef tagPALETTEENTRY type_74[16];
typedef tagPALETTEENTRY type_75[16];
typedef tagPALETTEENTRY type_76[16];
typedef tagPALETTEENTRY type_77[16];
typedef tagPALETTEENTRY type_78[16];
typedef tagPALETTEENTRY type_79[16];
typedef tagPALETTEENTRY* type_80[32];
typedef tagPALETTEENTRY type_81[16];
typedef tagPALETTEENTRY type_82[16];
typedef tagPALETTEENTRY type_83[16];
typedef tagPALETTEENTRY type_84[16];
typedef tagPALETTEENTRY* type_85[32];
typedef tagPALETTEENTRY type_86[16];
typedef tagPALETTEENTRY type_87[16];
typedef tagPALETTEENTRY type_88[16];
typedef tagPALETTEENTRY type_89[16];
typedef tagPALETTEENTRY* type_90[32];
typedef tagPALETTEENTRY type_91[16];
typedef tagPALETTEENTRY type_92[16];
typedef tagPALETTEENTRY type_93[16];
typedef tagPALETTEENTRY type_94[16];
typedef tagPALETTEENTRY* type_95[32];
typedef tagPALETTEENTRY type_96[16];

struct tagPALETTEENTRY
{
	unsigned char peRed;
	unsigned char peGreen;
	unsigned char peBlue;
	unsigned char peFlags;
};

tagPALETTEENTRY** lp_coltbl[6];
tagPALETTEENTRY* sprite_color[2];
tagPALETTEENTRY sprite_col1[16];
tagPALETTEENTRY sprite_col2[16];
tagPALETTEENTRY ascii_col[16];
tagPALETTEENTRY init_col[64];
tagPALETTEENTRY* lp_now[32];
tagPALETTEENTRY lpnowA[16];
tagPALETTEENTRY lpnowB[16];
tagPALETTEENTRY lpnowC[16];
tagPALETTEENTRY lpnowD[16];
tagPALETTEENTRY lpnowE[16];
tagPALETTEENTRY lpnowF[16];
tagPALETTEENTRY lpnowG[16];
tagPALETTEENTRY lpnowH[16];
tagPALETTEENTRY lpnowI[16];
tagPALETTEENTRY lpnowJ[16];
tagPALETTEENTRY lpnowK[16];
tagPALETTEENTRY lpnowL[16];
tagPALETTEENTRY lpnowM[16];
tagPALETTEENTRY lpnowN[16];
tagPALETTEENTRY lpnowO[16];
tagPALETTEENTRY lpnowP[16];
tagPALETTEENTRY lpnowQ[16];
tagPALETTEENTRY* lp_good[32];
tagPALETTEENTRY lpgoodA[16];
tagPALETTEENTRY lpgoodB[16];
tagPALETTEENTRY lpgoodC[16];
tagPALETTEENTRY lpgoodD[16];
tagPALETTEENTRY lpgoodE[16];
tagPALETTEENTRY lpgoodF[16];
tagPALETTEENTRY lpgoodG[16];
tagPALETTEENTRY lpgoodH[16];
tagPALETTEENTRY lpgoodI[16];
tagPALETTEENTRY lpgoodJ[16];
tagPALETTEENTRY lpgoodK[16];
tagPALETTEENTRY lpgoodL[16];
tagPALETTEENTRY lpgoodM[16];
tagPALETTEENTRY lpgoodN[16];
tagPALETTEENTRY lpgoodO[16];
tagPALETTEENTRY lpgoodP[16];
tagPALETTEENTRY lpgoodQ[16];
tagPALETTEENTRY* lp_bad[32];
tagPALETTEENTRY lpbadA[16];
tagPALETTEENTRY lpbadB[16];
tagPALETTEENTRY lpbadC[16];
tagPALETTEENTRY lpbadD[16];
tagPALETTEENTRY lpbadE[16];
tagPALETTEENTRY lpbadF[16];
tagPALETTEENTRY lpbadG[16];
tagPALETTEENTRY lpbadH[16];
tagPALETTEENTRY lpbadI[16];
tagPALETTEENTRY lpbadJ[16];
tagPALETTEENTRY lpbadK[16];
tagPALETTEENTRY lpbadL[16];
tagPALETTEENTRY lpbadM[16];
tagPALETTEENTRY lpbadN[16];
tagPALETTEENTRY lpbadO[16];
tagPALETTEENTRY lpbadP[16];
tagPALETTEENTRY lpbadQ[16];
tagPALETTEENTRY* lpbs_good[32];
tagPALETTEENTRY lpbsgoodA[16];
tagPALETTEENTRY lpbsgoodB[16];
tagPALETTEENTRY lpbsgoodC[16];
tagPALETTEENTRY lpbsgoodD[16];
tagPALETTEENTRY lpbsgoodE[16];
tagPALETTEENTRY lpbsgoodF[16];
tagPALETTEENTRY lpbsgoodG[16];
tagPALETTEENTRY lpbsgoodH[16];
tagPALETTEENTRY lpbsgoodI[16];
tagPALETTEENTRY lpbsgoodJ[16];
tagPALETTEENTRY lpbsgoodK[16];
tagPALETTEENTRY lpbsgoodL[16];
tagPALETTEENTRY lpbsgoodM[16];
tagPALETTEENTRY lpbsgoodN[16];
tagPALETTEENTRY lpbsgoodO[16];
tagPALETTEENTRY lpbsgoodP[16];
tagPALETTEENTRY lpbsgoodQ[16];
tagPALETTEENTRY* lpbs_bad[32];
tagPALETTEENTRY lpbsbadA[16];
tagPALETTEENTRY lpbsbadB[16];
tagPALETTEENTRY lpbsbadC[16];
tagPALETTEENTRY lpbsbadD[16];
tagPALETTEENTRY lpbsbadE[16];
tagPALETTEENTRY lpbsbadF[16];
tagPALETTEENTRY lpbsbadG[16];
tagPALETTEENTRY lpbsbadH[16];
tagPALETTEENTRY lpbsbadI[16];
tagPALETTEENTRY lpbsbadJ[16];
tagPALETTEENTRY lpbsbadK[16];
tagPALETTEENTRY lpbsbadL[16];
tagPALETTEENTRY lpbsbadM[16];
tagPALETTEENTRY lpbsbadN[16];
tagPALETTEENTRY lpbsbadO[16];
tagPALETTEENTRY lpbsbadP[16];
tagPALETTEENTRY lpbsbadQ[16];
short lpbs_timer[32];


